create or replace TABLE EMBED_DB_TEST.EXPERIAN_SCRUB.EMAIL (
	CUSTOMER_ID VARCHAR(134217728) NOT NULL,
	DATE_REPORTED DATE,
	EMAIL VARCHAR(134217728),
	BATCH_NO VARCHAR(7) NOT NULL,
	CREATED_AT DATE NOT NULL
);