create or replace TABLE EMBED_DB_TEST.EXPERIAN_SCRUB.PHONE (
	CUSTOMER_ID VARCHAR(134217728) NOT NULL,
	PHONE VARCHAR(134217728),
	DATE_REPORTED DATE,
	BATCH_NO VARCHAR(7) NOT NULL,
	CREATED_AT DATE NOT NULL
);