from snowflake.snowpark.types import StringType, StructField, StructType, IntegerType

schema_for_temp_table = StructType([
            StructField("BATCH", StringType()),
            StructField("FILE_NAME", StringType()),
            StructField("COUNT", IntegerType())    
        ])

schema_for_address_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("ADDRESS", StringType()),
        StructField("PINCODE", StringType()),
        StructField("DATE_REPORTED", StringType()),
    ]
)

schema_for_employment_file = StructType(
    [
        StructField("ACCT_KEY", StringType()),
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("INCOME", StringType()),
        StructField("INCOME_FREQ", StringType()),
        StructField("OCCUP_STATUS_CD", StringType()),
        StructField("RPT_DT", StringType()),
        StructField("BANK_TYPE", StringType()),
    ]
)

schema_for_fintech_enquiries_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("INQ_RQST_DT", StringType()),
        StructField("total_ecv_inquiries", StringType()),
    ]
)

schema_for_propensity_score_file = StructType(
    [
        StructField("cust_id", StringType(), nullable=False),
        StructField("Score", StringType()),
    ]
)



schema_for_AR_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("ACCT_KEY", StringType()),
        StructField("ACCOUNT_NB", StringType()),
        StructField("M_SUB_ID", StringType()),
        StructField("ACCT_TYPE_CD", StringType()),
        StructField("OPEN_DT", StringType()),
        StructField("ACTUAL_PAYMENT_AM", StringType()),
        StructField("ASSET_CLASS_CD", StringType()),
        StructField("BALANCE_AM", StringType()),
        StructField("BALANCE_DT", StringType()),
        StructField("CHARGE_OFF_AM", StringType()),
        StructField("CLOSED_DT", StringType()),
        StructField("CREDIT_LIMIT_AM", StringType()),
        StructField("DAYS_PAST_DUE", StringType()),
        StructField("DFLT_STATUS_DT", StringType()),
        StructField("LAST_PAYMENT_DT", StringType()),
        StructField("ORIG_LOAN_AM", StringType()),
        StructField("PAST_DUE_AM", StringType()),
        StructField("PAYMENT_HISTORY_GRID", StringType()),
        StructField("SUIT_FILED_WILLFUL_DFLT", StringType()),
        StructField("WRITTEN_OFF_AND_SETTLED_STATUS", StringType()),
        StructField("WRITE_OFF_STATUS_DT", StringType()),
        StructField("RESPONSIBILITY_CD", StringType()),
        StructField("EMI_AMT", StringType()),
        StructField("INTEREST_RATE", StringType()),
        StructField("TENURE", StringType()),
        StructField("PORTFOLIO_RATING_TYPE_CD", StringType()),
        StructField("ACTUAL_PAYMENT_AM_01", StringType()),
        StructField("ACTUAL_PAYMENT_AM_02", StringType()),
        StructField("ACTUAL_PAYMENT_AM_03", StringType()),
        StructField("ACTUAL_PAYMENT_AM_04", StringType()),
        StructField("ACTUAL_PAYMENT_AM_05", StringType()),
        StructField("ACTUAL_PAYMENT_AM_06", StringType()),
        StructField("ACTUAL_PAYMENT_AM_07", StringType()),
        StructField("ACTUAL_PAYMENT_AM_08", StringType()),
        StructField("ACTUAL_PAYMENT_AM_09", StringType()),
        StructField("ACTUAL_PAYMENT_AM_10", StringType()),
        StructField("ACTUAL_PAYMENT_AM_11", StringType()),
        StructField("ACTUAL_PAYMENT_AM_12", StringType()),
        StructField("ACTUAL_PAYMENT_AM_13", StringType()),
        StructField("ACTUAL_PAYMENT_AM_14", StringType()),
        StructField("ACTUAL_PAYMENT_AM_15", StringType()),
        StructField("ACTUAL_PAYMENT_AM_16", StringType()),
        StructField("ACTUAL_PAYMENT_AM_17", StringType()),
        StructField("ACTUAL_PAYMENT_AM_18", StringType()),
        StructField("ACTUAL_PAYMENT_AM_19", StringType()),
        StructField("ACTUAL_PAYMENT_AM_20", StringType()),
        StructField("ACTUAL_PAYMENT_AM_21", StringType()),
        StructField("ACTUAL_PAYMENT_AM_22", StringType()),
        StructField("ACTUAL_PAYMENT_AM_23", StringType()),
        StructField("ACTUAL_PAYMENT_AM_24", StringType()),
        StructField("ACTUAL_PAYMENT_AM_25", StringType()),
        StructField("ACTUAL_PAYMENT_AM_26", StringType()),
        StructField("ACTUAL_PAYMENT_AM_27", StringType()),
        StructField("ACTUAL_PAYMENT_AM_28", StringType()),
        StructField("ACTUAL_PAYMENT_AM_29", StringType()),
        StructField("ACTUAL_PAYMENT_AM_30", StringType()),
        StructField("ACTUAL_PAYMENT_AM_31", StringType()),
        StructField("ACTUAL_PAYMENT_AM_32", StringType()),
        StructField("ACTUAL_PAYMENT_AM_33", StringType()),
        StructField("ACTUAL_PAYMENT_AM_34", StringType()),
        StructField("ACTUAL_PAYMENT_AM_35", StringType()),
        StructField("ACTUAL_PAYMENT_AM_36", StringType()),
        StructField("ACTUAL_PAYMENT_AM_37", StringType()),
        StructField("ACTUAL_PAYMENT_AM_38", StringType()),
        StructField("ACTUAL_PAYMENT_AM_39", StringType()),
        StructField("ACTUAL_PAYMENT_AM_40", StringType()),
        StructField("ACTUAL_PAYMENT_AM_41", StringType()),
        StructField("ACTUAL_PAYMENT_AM_42", StringType()),
        StructField("ACTUAL_PAYMENT_AM_43", StringType()),
        StructField("ACTUAL_PAYMENT_AM_44", StringType()),
        StructField("ACTUAL_PAYMENT_AM_45", StringType()),
        StructField("ACTUAL_PAYMENT_AM_46", StringType()),
        StructField("ACTUAL_PAYMENT_AM_47", StringType()),
        StructField("ACTUAL_PAYMENT_AM_48", StringType()),
        StructField("BALANCE_AM_01", StringType()),
        StructField("BALANCE_AM_02", StringType()),
        StructField("BALANCE_AM_03", StringType()),
        StructField("BALANCE_AM_04", StringType()),
        StructField("BALANCE_AM_05", StringType()),
        StructField("BALANCE_AM_06", StringType()),
        StructField("BALANCE_AM_07", StringType()),
        StructField("BALANCE_AM_08", StringType()),
        StructField("BALANCE_AM_09", StringType()),
        StructField("BALANCE_AM_10", StringType()),
        StructField("BALANCE_AM_11", StringType()),
        StructField("BALANCE_AM_12", StringType()),
        StructField("BALANCE_AM_13", StringType()),
        StructField("BALANCE_AM_14", StringType()),
        StructField("BALANCE_AM_15", StringType()),
        StructField("BALANCE_AM_16", StringType()),
        StructField("BALANCE_AM_17", StringType()),
        StructField("BALANCE_AM_18", StringType()),
        StructField("BALANCE_AM_19", StringType()),
        StructField("BALANCE_AM_20", StringType()),
        StructField("BALANCE_AM_21", StringType()),
        StructField("BALANCE_AM_22", StringType()),
        StructField("BALANCE_AM_23", StringType()),
        StructField("BALANCE_AM_24", StringType()),
        StructField("BALANCE_AM_25", StringType()),
        StructField("BALANCE_AM_26", StringType()),
        StructField("BALANCE_AM_27", StringType()),
        StructField("BALANCE_AM_28", StringType()),
        StructField("BALANCE_AM_29", StringType()),
        StructField("BALANCE_AM_30", StringType()),
        StructField("BALANCE_AM_31", StringType()),
        StructField("BALANCE_AM_32", StringType()),
        StructField("BALANCE_AM_33", StringType()),
        StructField("BALANCE_AM_34", StringType()),
        StructField("BALANCE_AM_35", StringType()),
        StructField("BALANCE_AM_36", StringType()),
        StructField("BALANCE_AM_37", StringType()),
        StructField("BALANCE_AM_38", StringType()),
        StructField("BALANCE_AM_39", StringType()),
        StructField("BALANCE_AM_40", StringType()),
        StructField("BALANCE_AM_41", StringType()),
        StructField("BALANCE_AM_42", StringType()),
        StructField("BALANCE_AM_43", StringType()),
        StructField("BALANCE_AM_44", StringType()),
        StructField("BALANCE_AM_45", StringType()),
        StructField("BALANCE_AM_46", StringType()),
        StructField("BALANCE_AM_47", StringType()),
        StructField("BALANCE_AM_48", StringType()),
        StructField("CREDIT_LIMIT_AM_01", StringType()),
        StructField("CREDIT_LIMIT_AM_02", StringType()),
        StructField("CREDIT_LIMIT_AM_03", StringType()),
        StructField("CREDIT_LIMIT_AM_04", StringType()),
        StructField("CREDIT_LIMIT_AM_05", StringType()),
        StructField("CREDIT_LIMIT_AM_06", StringType()),
        StructField("CREDIT_LIMIT_AM_07", StringType()),
        StructField("CREDIT_LIMIT_AM_08", StringType()),
        StructField("CREDIT_LIMIT_AM_09", StringType()),
        StructField("CREDIT_LIMIT_AM_10", StringType()),
        StructField("CREDIT_LIMIT_AM_11", StringType()),
        StructField("CREDIT_LIMIT_AM_12", StringType()),
        StructField("CREDIT_LIMIT_AM_13", StringType()),
        StructField("CREDIT_LIMIT_AM_14", StringType()),
        StructField("CREDIT_LIMIT_AM_15", StringType()),
        StructField("CREDIT_LIMIT_AM_16", StringType()),
        StructField("CREDIT_LIMIT_AM_17", StringType()),
        StructField("CREDIT_LIMIT_AM_18", StringType()),
        StructField("CREDIT_LIMIT_AM_19", StringType()),
        StructField("CREDIT_LIMIT_AM_20", StringType()),
        StructField("CREDIT_LIMIT_AM_21", StringType()),
        StructField("CREDIT_LIMIT_AM_22", StringType()),
        StructField("CREDIT_LIMIT_AM_23", StringType()),
        StructField("CREDIT_LIMIT_AM_24", StringType()),
        StructField("CREDIT_LIMIT_AM_25", StringType()),
        StructField("CREDIT_LIMIT_AM_26", StringType()),
        StructField("CREDIT_LIMIT_AM_27", StringType()),
        StructField("CREDIT_LIMIT_AM_28", StringType()),
        StructField("CREDIT_LIMIT_AM_29", StringType()),
        StructField("CREDIT_LIMIT_AM_30", StringType()),
        StructField("CREDIT_LIMIT_AM_31", StringType()),
        StructField("CREDIT_LIMIT_AM_32", StringType()),
        StructField("CREDIT_LIMIT_AM_33", StringType()),
        StructField("CREDIT_LIMIT_AM_34", StringType()),
        StructField("CREDIT_LIMIT_AM_35", StringType()),
        StructField("CREDIT_LIMIT_AM_36", StringType()),
        StructField("CREDIT_LIMIT_AM_37", StringType()),
        StructField("CREDIT_LIMIT_AM_38", StringType()),
        StructField("CREDIT_LIMIT_AM_39", StringType()),
        StructField("CREDIT_LIMIT_AM_40", StringType()),
        StructField("CREDIT_LIMIT_AM_41", StringType()),
        StructField("CREDIT_LIMIT_AM_42", StringType()),
        StructField("CREDIT_LIMIT_AM_43", StringType()),
        StructField("CREDIT_LIMIT_AM_44", StringType()),
        StructField("CREDIT_LIMIT_AM_45", StringType()),
        StructField("CREDIT_LIMIT_AM_46", StringType()),
        StructField("CREDIT_LIMIT_AM_47", StringType()),
        StructField("CREDIT_LIMIT_AM_48", StringType()),
        StructField("PAST_DUE_AM_01", StringType()),
        StructField("PAST_DUE_AM_02", StringType()),
        StructField("PAST_DUE_AM_03", StringType()),
        StructField("PAST_DUE_AM_04", StringType()),
        StructField("PAST_DUE_AM_05", StringType()),
        StructField("PAST_DUE_AM_06", StringType()),
        StructField("PAST_DUE_AM_07", StringType()),
        StructField("PAST_DUE_AM_08", StringType()),
        StructField("PAST_DUE_AM_09", StringType()),
        StructField("PAST_DUE_AM_10", StringType()),
        StructField("PAST_DUE_AM_11", StringType()),
        StructField("PAST_DUE_AM_12", StringType()),
        StructField("PAST_DUE_AM_13", StringType()),
        StructField("PAST_DUE_AM_14", StringType()),
        StructField("PAST_DUE_AM_15", StringType()),
        StructField("PAST_DUE_AM_16", StringType()),
        StructField("PAST_DUE_AM_17", StringType()),
        StructField("PAST_DUE_AM_18", StringType()),
        StructField("PAST_DUE_AM_19", StringType()),
        StructField("PAST_DUE_AM_20", StringType()),
        StructField("PAST_DUE_AM_21", StringType()),
        StructField("PAST_DUE_AM_22", StringType()),
        StructField("PAST_DUE_AM_23", StringType()),
        StructField("PAST_DUE_AM_24", StringType()),
        StructField("PAST_DUE_AM_25", StringType()),
        StructField("PAST_DUE_AM_26", StringType()),
        StructField("PAST_DUE_AM_27", StringType()),
        StructField("PAST_DUE_AM_28", StringType()),
        StructField("PAST_DUE_AM_29", StringType()),
        StructField("PAST_DUE_AM_30", StringType()),
        StructField("PAST_DUE_AM_31", StringType()),
        StructField("PAST_DUE_AM_32", StringType()),
        StructField("PAST_DUE_AM_33", StringType()),
        StructField("PAST_DUE_AM_34", StringType()),
        StructField("PAST_DUE_AM_35", StringType()),
        StructField("PAST_DUE_AM_36", StringType()),
        StructField("PAST_DUE_AM_37", StringType()),
        StructField("PAST_DUE_AM_38", StringType()),
        StructField("PAST_DUE_AM_39", StringType()),
        StructField("PAST_DUE_AM_40", StringType()),
        StructField("PAST_DUE_AM_41", StringType()),
        StructField("PAST_DUE_AM_42", StringType()),
        StructField("PAST_DUE_AM_43", StringType()),
        StructField("PAST_DUE_AM_44", StringType()),
        StructField("PAST_DUE_AM_45", StringType()),
        StructField("PAST_DUE_AM_46", StringType()),
        StructField("PAST_DUE_AM_47", StringType()),
        StructField("PAST_DUE_AM_48", StringType()),
        StructField("PAYMENT_RATING_CD_01", StringType()),
        StructField("PAYMENT_RATING_CD_02", StringType()),
        StructField("PAYMENT_RATING_CD_03", StringType()),
        StructField("PAYMENT_RATING_CD_04", StringType()),
        StructField("PAYMENT_RATING_CD_05", StringType()),
        StructField("PAYMENT_RATING_CD_06", StringType()),
        StructField("PAYMENT_RATING_CD_07", StringType()),
        StructField("PAYMENT_RATING_CD_08", StringType()),
        StructField("PAYMENT_RATING_CD_09", StringType()),
        StructField("PAYMENT_RATING_CD_10", StringType()),
        StructField("PAYMENT_RATING_CD_11", StringType()),
        StructField("PAYMENT_RATING_CD_12", StringType()),
        StructField("PAYMENT_RATING_CD_13", StringType()),
        StructField("PAYMENT_RATING_CD_14", StringType()),
        StructField("PAYMENT_RATING_CD_15", StringType()),
        StructField("PAYMENT_RATING_CD_16", StringType()),
        StructField("PAYMENT_RATING_CD_17", StringType()),
        StructField("PAYMENT_RATING_CD_18", StringType()),
        StructField("PAYMENT_RATING_CD_19", StringType()),
        StructField("PAYMENT_RATING_CD_20", StringType()),
        StructField("PAYMENT_RATING_CD_21", StringType()),
        StructField("PAYMENT_RATING_CD_22", StringType()),
        StructField("PAYMENT_RATING_CD_23", StringType()),
        StructField("PAYMENT_RATING_CD_24", StringType()),
        StructField("DAYS_PAST_DUE_01", StringType()),
        StructField("DAYS_PAST_DUE_02", StringType()),
        StructField("DAYS_PAST_DUE_03", StringType()),
        StructField("DAYS_PAST_DUE_04", StringType()),
        StructField("DAYS_PAST_DUE_05", StringType()),
        StructField("DAYS_PAST_DUE_06", StringType()),
        StructField("DAYS_PAST_DUE_07", StringType()),
        StructField("DAYS_PAST_DUE_08", StringType()),
        StructField("DAYS_PAST_DUE_09", StringType()),
        StructField("DAYS_PAST_DUE_10", StringType()),
        StructField("DAYS_PAST_DUE_11", StringType()),
        StructField("DAYS_PAST_DUE_12", StringType()),
        StructField("DAYS_PAST_DUE_13", StringType()),
        StructField("DAYS_PAST_DUE_14", StringType()),
        StructField("DAYS_PAST_DUE_15", StringType()),
        StructField("DAYS_PAST_DUE_16", StringType()),
        StructField("DAYS_PAST_DUE_17", StringType()),
        StructField("DAYS_PAST_DUE_18", StringType()),
        StructField("DAYS_PAST_DUE_19", StringType()),
        StructField("DAYS_PAST_DUE_20", StringType()),
        StructField("DAYS_PAST_DUE_21", StringType()),
        StructField("DAYS_PAST_DUE_22", StringType()),
        StructField("DAYS_PAST_DUE_23", StringType()),
        StructField("DAYS_PAST_DUE_24", StringType()),
        StructField("DAYS_PAST_DUE_25", StringType()),
        StructField("DAYS_PAST_DUE_26", StringType()),
        StructField("DAYS_PAST_DUE_27", StringType()),
        StructField("DAYS_PAST_DUE_28", StringType()),
        StructField("DAYS_PAST_DUE_29", StringType()),
        StructField("DAYS_PAST_DUE_30", StringType()),
        StructField("DAYS_PAST_DUE_31", StringType()),
        StructField("DAYS_PAST_DUE_32", StringType()),
        StructField("DAYS_PAST_DUE_33", StringType()),
        StructField("DAYS_PAST_DUE_34", StringType()),
        StructField("DAYS_PAST_DUE_35", StringType()),
        StructField("DAYS_PAST_DUE_36", StringType()),
        StructField("DAYS_PAST_DUE_37", StringType()),
        StructField("DAYS_PAST_DUE_38", StringType()),
        StructField("DAYS_PAST_DUE_39", StringType()),
        StructField("DAYS_PAST_DUE_40", StringType()),
        StructField("DAYS_PAST_DUE_41", StringType()),
        StructField("DAYS_PAST_DUE_42", StringType()),
        StructField("DAYS_PAST_DUE_43", StringType()),
        StructField("DAYS_PAST_DUE_44", StringType()),
        StructField("DAYS_PAST_DUE_45", StringType()),
        StructField("DAYS_PAST_DUE_46", StringType()),
        StructField("DAYS_PAST_DUE_47", StringType()),
        StructField("DAYS_PAST_DUE_48", StringType()),
        StructField("LAST_PYMT_DT_01", StringType()),
        StructField("LAST_PYMT_DT_02", StringType()),
        StructField("LAST_PYMT_DT_03", StringType()),
        StructField("LAST_PYMT_DT_04", StringType()),
        StructField("LAST_PYMT_DT_05", StringType()),
        StructField("LAST_PYMT_DT_06", StringType()),
        StructField("LAST_PYMT_DT_07", StringType()),
        StructField("LAST_PYMT_DT_08", StringType()),
        StructField("LAST_PYMT_DT_09", StringType()),
        StructField("LAST_PYMT_DT_10", StringType()),
        StructField("LAST_PYMT_DT_11", StringType()),
        StructField("LAST_PYMT_DT_12", StringType()),
        StructField("LAST_PYMT_DT_13", StringType()),
        StructField("LAST_PYMT_DT_14", StringType()),
        StructField("LAST_PYMT_DT_15", StringType()),
        StructField("LAST_PYMT_DT_16", StringType()),
        StructField("LAST_PYMT_DT_17", StringType()),
        StructField("LAST_PYMT_DT_18", StringType()),
        StructField("LAST_PYMT_DT_19", StringType()),
        StructField("LAST_PYMT_DT_20", StringType()),
        StructField("LAST_PYMT_DT_21", StringType()),
        StructField("LAST_PYMT_DT_22", StringType()),
        StructField("LAST_PYMT_DT_23", StringType()),
        StructField("LAST_PYMT_DT_24", StringType()),
        StructField("LAST_PYMT_DT_25", StringType()),
        StructField("LAST_PYMT_DT_26", StringType()),
        StructField("LAST_PYMT_DT_27", StringType()),
        StructField("LAST_PYMT_DT_28", StringType()),
        StructField("LAST_PYMT_DT_29", StringType()),
        StructField("LAST_PYMT_DT_30", StringType()),
        StructField("LAST_PYMT_DT_31", StringType()),
        StructField("LAST_PYMT_DT_32", StringType()),
        StructField("LAST_PYMT_DT_33", StringType()),
        StructField("LAST_PYMT_DT_34", StringType()),
        StructField("LAST_PYMT_DT_35", StringType()),
        StructField("LAST_PYMT_DT_36", StringType()),
        StructField("LAST_PYMT_DT_37", StringType()),
        StructField("LAST_PYMT_DT_38", StringType()),
        StructField("LAST_PYMT_DT_39", StringType()),
        StructField("LAST_PYMT_DT_40", StringType()),
        StructField("LAST_PYMT_DT_41", StringType()),
        StructField("LAST_PYMT_DT_42", StringType()),
        StructField("LAST_PYMT_DT_43", StringType()),
        StructField("LAST_PYMT_DT_44", StringType()),
        StructField("LAST_PYMT_DT_45", StringType()),
        StructField("LAST_PYMT_DT_46", StringType()),
        StructField("LAST_PYMT_DT_47", StringType()),
        StructField("LAST_PYMT_DT_48", StringType()),

    ]
)

schema_for_ENQ_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("INQ_PURP_CD", StringType()),
        StructField("INQ_DATE", StringType()),
        StructField("M_SUB_ID", StringType()),
        StructField("AMOUNT", StringType()),
    ]
)

schema_for_email_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("EMAIL", StringType()),
        StructField("DATE_REPORTED", StringType()),
    ]
)

schema_for_id_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("PAN", StringType()),
        StructField("PASSPORT", StringType()),
        StructField("VOTER_ID", StringType()),
        StructField("UID", StringType()),
        StructField("RATION_CARD", StringType()),
        StructField("DRIVING_LICENSE", StringType()),
    ]
)

schema_for_name_dob_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("FULL_NAME", StringType()),
        StructField("DOB", StringType()),
        StructField("GENDER", StringType()),
    ]
)

schema_for_phone_file = StructType(
    [
        StructField("CUSTOMER_ID", StringType(), nullable=False),
        StructField("PHONE", StringType()),
        StructField("DATE_REPORTED", StringType()),
    ]
)

schema_for_reference_file = StructType(
    [
        StructField("MEMBER_REFERENCE", StringType(), nullable=False),
        StructField("NAME", StringType()),
        StructField("PAN_NO", StringType()),
        StructField("DATE_OF_BIRTH", StringType()),
        StructField("PHONE_NUMBER", StringType()),
        StructField("PIN", StringType()),
    ]
)

schema_for_score_file = StructType(
    [
        StructField("CUST_ID", StringType(), nullable=False),
        StructField("Score_V3", StringType()),
    ]
)
