
account_types_codes = {
    "5": ["Credit Card", "revolving"],
    "47": ["Instalment Loan, Automobile", "auto"],
    "58": ["Instalment Loan, Mortgage", "mortgage"],
    "121": ["Banking, Overdraft", "over_draft"],
    "123": ["Loan, Personal Cash", "personal"],
    "130": ["Loan, Student", "personal"],
    "167": ["Microfinance, Business", "business"],
    "168": ["Microfinance, Housing", "mortgage"],
    "169": ["Microfinance, Personal", "personal"],
    "170": ["Microfinance, Other", "others"],
    "172": ["Instalment Loan, Commercial Vehicle", "auto"],
    "173": ["Instalment Loan, Two-Wheeler", "auto"],
    "175": ["Business Loan Against Bank Deposits", "securepl"],
    "176": ["Business Loan - General", "business"],
    "177": ["Business Loan - Priority Sector - Small Business", "business"],
    "178": ["Business Loan - Priority Sector - Agriculture", "business"],
    "179": ["Business Loan - Priority Sector - Others", "business"],
    "181": ["Credit Facility, Non-Funded", "credit_line"],
    "184": ["Loan Against Bank Deposits", "securepl"],
    "185": ["Loan Against Shares/Securities", "securepl"],
    "187": ["Loan to Professional", "personal"],
    "189": ["Loan, Consumer", "consumer"],
    "191": ["Loan, Gold", "securepl"],
    "195": ["Loan, Property", "securepl"],
    "196": ["Loan, Staff", "personal"],
    "197": ["Non-Funded Credit Facility, General", "business"],
    "198": ["Non-Funded Credit Facility, Priority Sector - Small Business", "business"],
    "199": ["Non-Funded Credit Facility, Priority Sector - Agriculture", "business"],
    "200": ["Non-Funded Credit Facility, Priority Sector - Others", "business"],
    "213": ["Corporate Credit Card", "revolving"],
    "214": ["Credit Card, Fleet", "revolving"],
    "215": ["Service, Telco - Broadband", "telco"],
    "216": ["Service, Telco - Landline", "telco"],
    "217": ["Service, Telco - Wireless", "telco"],
    "219": ["Leasing, Other", "others"],
    "220": ["Secured Credit Card", "revolving"],
    "221": ["Used Car Loan", "auto"],
    "222": ["Construction Equipment Loan", "business"],
    "223": ["Tractor Loan", "business"],
    "224": ["Kisan Credit Card", "revolving"],
    "225": ["Loan on Credit Card", "personal"],
    "226": ["Pradhan Mantri JDY (Over Draft)", "over_draft"],
    "227": ["Mudra Loan (Shishu/Kishor/Tarun)", "personal"],
    "228": ["Business Loan - Unsecured", "business"],
    "240": ["Pradhan Mantri Awas Yojna", "others"],
    "241": ["Business Loan - Secured", "business"],
    "242": ["Short Term Personal Loan [Unsecured]", "personal"],
    "243": ["Priority Sector Gold Loan [Secured]", "securepl"],
    "244": ["Temporary Overdraft [Unsecured]", "over_draft"],
    "245": ["P2P Personal Loan", "personal"],
    "246": ["P2P Auto Loan", "auto"],
    "247": ["P2P Education Loan", "personal"],
    "248": ["GECL Loan Secured", "credit_line"],
    "249": ["GECL Loan Unsecured", "credit_line"],
    "999": ["Other", "others"],
}

carded_acct_types = [
    "Credit Card",
    "Corporate Credit Card",
    "Credit Card, Fleet",
    "Secured Credit Card",
    "Kisan Credit Card",
]

inq_types_codes = {
    "1": "Agriculture Loan",
    "2": "Auto Loan",
    "3": "Business Loan",
    "4": "Commercial Vehicle Loans",
    "5": "Construction Equipment Loan",
    "6": "Consumer Search",
    "7": "Credit Card",
    "8": "Education Loan",
    "9": "Leasing",
    "10": "Loan Against Collateral",
    "11": "Microfinance",
    "12": "Non-Funded Credit Facility",
    "13": "Personal Loan",
    "14": "Property Loan",
    "15": "Telecom",
    "16": "Two/Three Wheeler Loan",
    "17": "Working Capital Loan",
    "18": "Consumer Loan",
    "19": "Credit Review",
    "99": "Others",
}

suit_filed_wilful_default_codes = {
    "200": "Restructured",
    "201": "Suit Filed",
    "202": "Wilful Default",
    "203": "Suit Filed (Wilful Default)",
    "204": "Written Off",
    "205": "Suit Filed & Written Off",
    "206": "Wilful Default & Written Off",
    "207": "Suit Filed (Wilful Default) & Written Off",
    "208": "Settled",
    "209": "Post (WO) Settled",
    "00": "No Suit Filed",
    "0": "No Suit Filed",
    "01": "Suit Filed",
    "1": "Suit Filed",
    "02": "Wilful Default",
    "2": "Wilful Default",
    "03": "Suit Filed (Wilful Default)",
    "3": "Suit Filed (Wilful Default)",
}

written_off_settled_status_codes = {
    "00": "Restructure Loan",
    "01": "Restructure Loan (Govt. Mandated)",
    "02": "Written-off",
    "03": "Settled",
    "04": "Post (WO) Settled",
    "05": "Account Sold",
    "06": "Written Off and Account Sold",
    "07": "Account Purchased",
    "08": "Account Purchased and Written Off",
    "09": "Account Purchased and Settled",
    "10": "Account Purchased and Restructured",
    "11": "Restructured due to Natural Calamity",
    "12": "Restructured due to COVID-19",
    "99": "Clear existing status",
}

decline_categories = [
    "Suit Filed",
    "Wilful Default",
    "Suit Filed (Wilful Default)",
    "Written Off",
    "Suit Filed & Written Off",
    "Wilful Default & Written Off",
    "Suit Filed (Wilful Default) & Written Off",
    "Settled",
    "Post (WO) Settled",
    "Suit Filed",
    "Suit Filed",
    "Wilful Default",
    "Wilful Default",
    "Suit Filed (Wilful Default)",
    "Suit Filed (Wilful Default)",
    "Written-off",
    "Settled",
    "Post (WO) Settled",
    "Written Off and Account Sold",
    "Account Purchased and Written Off",
    "Account Purchased and Settled",
]

demog_req_cols = [
    "CRN",
    "CUSTOMER_ID",
    "MEMBER_REFERENCE",
    "MASKED_PAN",
    "GENDER",
    "DOB",
    "SCORE",
    "PINCODE",
    "PINCODE_LIST",
]
enquiry_req_cols = ["CUSTOMER_ID", "INQ_PURP_CD", "INQ_DATE", "AMOUNT"]

date_cols = [
    "DATE_REPORTED",
    "INQUIRY_DATE",
    "REPORTED_DATE",
    "DISBURSED_DT",
    "CLOSE_DT",
    "CLOSED_DT",
    "LAST_PAYMENT_DATE",
    "WRITE_OFF_DATE",
    "DOB",
    "DATE_OF_BIRTH",
    "RETRO_DT",
    "INQ_DATE",
    "BALANCE_DT",
    "OPEN_DT",
    'DFLT_STATUS_DT',
    'LAST_PAYMENT_DT','DATECLOSED','DATEOPENED','DATEREPORTED'
]

amount_cols = [
    "CREDIT_LIMIT",
    "DISBURSED_AMT",
    "CURRENT_BAL",
    "OVERDUE_AMT",
    "WRITE_OFF_AMT",
    "INCOME",
    "AMOUNT",
]

cols_mapping = {
    "DATE_REPORTED": "DateReported_trades",
    "DISBURSED_DT": "DATE_OPENED",
    "CLOSE_DT": "DATE_CLOSED",
    # "LAST_PAYMENT_DATE": "date_lstpmt",
    # "WRITE_OFF_DATE": "date_wo",
    "CREATED_AT" : 'BCC_DATE',
    "CREDIT_LIMIT" : 'CREDITLIMIT',
    "OVERDUE_AMT" : 'OVER_DUE_AMOUNT',
    "DISBURSED_AMT": "HIGHCREDITSANCTIONEDAMOUNT",
    "CURRENT_BAL": "OUT_STANDING_BALANCE",
    "WRITE_OFF_AMT" : "WRITTENOFFAMOUNTTOTAL",
    
}

experian_read_format  = {
            "PARSE_HEADER": True,
            "FIELD_DELIMITER": "|",
            "NULL_IF": ("NULL", "NUL", ""),
            "EMPTY_FIELD_AS_NULL": True,
            "ERROR_ON_COLUMN_COUNT_MISMATCH": True,
            "ON_ERROR": "CONTINUE","FIELD_OPTIONALLY_ENCLOSED_BY": '"'
        }

equifax_read_format =  {
        "PARSE_HEADER": True,
        "FIELD_DELIMITER": "|",
        "NULL_IF": ("NULL", "NUL", ""),
        "EMPTY_FIELD_AS_NULL": True,
        "ERROR_ON_COLUMN_COUNT_MISMATCH": True,
        "ON_ERROR": "CONTINUE","FIELD_OPTIONALLY_ENCLOSED_BY": '"'
    }
